# Generated by Django 5.2 on 2025-04-17 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
