# Generated by Django 5.2 on 2025-04-22 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='criado_em',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='order',
            name='valor_total',
        ),
    ]
