# Generated by Django 5.2 on 2025-04-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_rename_criado_em_order_data_remove_order_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='valor_total_pedido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
