# Generated by Django 5.2 on 2025-04-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_order_valor_total_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='valor_total_pedido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
