# Generated by Django 5.2.1 on 2025-05-28 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor', models.BooleanField(default=False)),
                ('foto', models.ImageField(default='uploads/fotos_perfil/DefaultProfileImage.png', upload_to='uploads/fotos_perfil/')),
                ('bios', models.CharField(default='Olá, este é o meu Perfil!', max_length=255)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
