# Generated by Django 5.2 on 2025-04-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_profile_bios_profile_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='uploads/fotos_perfil/DefaultProfileImage.png', upload_to='uploads/fotos_perfil/'),
        ),
    ]
