# Generated by Django 5.2 on 2025-04-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_alter_profile_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bios',
            field=models.CharField(default='Olá, este é o meu Perfil!', max_length=255),
        ),
    ]
