# Generated by Django 5.2 on 2025-04-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0006_carrinho_itemcarrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrinho',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
