# Generated by Django 5.2 on 2025-04-22 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_rename_criado_em_order_data_remove_order_valor_total'),
        ('Usuario', '0007_alter_itemcarrinho_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Store.order')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.produto')),
            ],
        ),
    ]
