# Generated by Django 5.2 on 2025-04-22 04:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_order_valor_total_pedido'),
        ('Usuario', '0008_itemorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorder',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='Store.produto'),
        ),
        migrations.AlterField(
            model_name='itemorder',
            name='quantidade',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
