# Generated by Django 5.2.1 on 2025-05-23 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_rename_status_order_status_pagamento_and_more'),
        ('Usuario', '0009_alter_itemorder_produto_alter_itemorder_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorder',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='Store.produto'),
        ),
    ]
