name: Pipeline Unimar-Ecommerce
#teste
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name : Checkout do código
        uses: actions/checkout@v3

      - name: Configurar ambiente Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Checar migrations pendentes
        run: python manage.py makemigrations --check --dry-run

      - name: Rodar testes com coverage
        run: |
          coverage run manage.py test
          coverage report

      - name: Gerar relatório de cobertura em HTML
        run: coverage html

      - name: Publicar HTML do coverage como artefato
        uses: actions/upload-artifact@v4
        with:
          name: cobertura-html
          path: htmlcov
